name: Lambda Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy-lambda:
    strategy:
      matrix:
        lambda-function: [lambda-google-translate] # , lambda-sqs-consumer, lambda-sqs-trigger

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./src/${{ matrix.lambda-function }}/requirements.txt

      - name: Copy code to rootdir
        run: |
          cp -r ./src/${{ matrix.lambda-function }}/* ./

      - name: Zipping files
        run: zip -r ./deploy.zip . -x '.github/*' 'src/*' 'README.md' '.git'
        shell: bash

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
          --function-name ${{ matrix.lambda-function }} \
          --zip-file fileb://deploy.zip
